version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: CodeClimate Test Reporter set up
          command: 'curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter'
      - run:
          name: Notifying CodeClimate of a pending report
          command: './cc-test-reporter before-build'
      - run:
          name: Installing pipenv
          command: 'pip install pipenv'
      - run:
          name: Install packages
          command: 'pipenv install --dev'
      - run:
          name: Running tests
          command: 'pipenv run coverage run --source=. -m pytest -v'
      - run:
          name: Sending coverage report to CodeClimate
          command: './cc-test-reporter after-build --exit-code $EXIT_CODE'