version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Installing pipenv
          command: 'pip install pipenv'
      - run:
          name: Install packages
          command: 'pipenv install --dev'
      - run:
          name: CodeClimate Test Reporter set up
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Notifying CodeClimate of a pending report
          command: './cc-test-reporter before-build'
      - run:
          name: Running tests
          command: |
            pipenv run coverage run --source=. -m pytest -v
            pipenv run coverage xml
      - run:
          name: Sending coverage report to CodeClimate
          command: './cc-test-reporter after-build --coverage-input-type coverage.py --id $CODE_CLIMATE_TEST_REPORTER_ID --exit-code $?'